server:
   port: 9091
   
cloud:
   aws:
      region:
         static: us-east-2
         auto: false
      credentials:
         access-key: AKIAWDHSUZB5KR2BK3UL
         secret-key: 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
      end-point:
         uri: https://sqs.us-east-2.amazonaws.com/419268184186/netsurfingzone-first-sqs